### ISSUE TITLE
Small hapi and joi version conflict

### ISSUE THREAD

**Issue by alexkreidler** [allenai/scholarphi#198] opened 2021-01-12 04:19 UTC
```
src/server.ts:89:11 - error TS2322: Type 'ObjectSchema<any>' is not assignable to type 'boolean | SchemaMap<any> | AnySchema | ArraySchema | AlternativesSchema | BinarySchema | BooleanSchema | ... 8 more ... | undefined'.
  Property 'regex' is missing in type 'import("/home/alex/c2/scholarphi/api/node_modules/@types/hapi__joi/index").ObjectSchema<any>' but required in type 'import("/home/alex/c2/scholarphi/api/node_modules/@types/hapi__hapi/node_modules/@types/hapi__joi/index").ObjectSchema<any>'.

89           payload: validation.logEntry,
             ~~~~~~~

  node_modules/@types/hapi__hapi/node_modules/@types/hapi__joi/index.d.ts:1648:9
    1648         regex(): this;
                 ~~~~~~~~~~~~~~
    'regex' is declared here.

[INFO] 22:35:17 Restarting: /home/alex/c2/scholarphi/api/src/server.ts has been modified
Compilation error in /home/alex/c2/scholarphi/api/src/server.ts
[ERROR] 22:35:18 ⨯ Unable to compile TypeScript:
src/server.ts:75:24 - error TS2352: Conversion of type '{ method: string; path: string; handler: (request: Request, h: ResponseToolkit) => Promise<ResponseObject>; options: { validate: { ...; }; }; }' to type 'ServerRoute' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Types of property 'options' are incompatible.
    Type '{ validate: { payload: Joi.ObjectSchema<any>; }; }' is not comparable to type 'RouteOptions | ((server: Server) => RouteOptions) | undefined'.
      Type '{ validate: { payload: Joi.ObjectSchema<any>; }; }' is not comparable to type 'RouteOptions'.
        The types of 'validate.payload' are incompatible between these types.
          Type 'ObjectSchema<any>' is not comparable to type 'boolean | SchemaMap<any> | AnySchema | ArraySchema | AlternativesSchema | BinarySchema | BooleanSchema | ... 8 more ... | undefined'.
            Property 'regex' is missing in type 'import("/home/alex/c2/scholarphi/api/node_modules/@types/hapi__joi/index").ObjectSchema<any>' but required in type 'import("/home/alex/c2/scholarphi/api/node_modules/@types/hapi__hapi/node_modules/@types/hapi__joi/index").ObjectSchema<any>'.

 75     this._server.route({
                           ~
 76       method: "POST",
    ~~~~~~~~~~~~~~~~~~~~~
... 
 99       },
    ~~~~~~~~
100     } as ServerRoute);
```

Bumped `@types/hapi__joi` to `^17.1.6`, now working fine! PR to follow.

**Comment by andrewhead** [comment] 2021-02-04 14:58
Hi @alexkreidler, thank you so much for reporting the issues and the PR! Sorry for the delay in my reply. I downloaded a fresh version of the API code, and have not been able to reproduce this error with the current package.json with `@types/hapi__joi` (despite the installed version of the types being a 16.0.2 as you mention in your post).

I realize it may be past the time when you have this info available, though what command were you running when this error appeared? What versions of node and npm were you using?

**Comment by andrewhead** [comment] 2021-03-02 14:22
As I was unable to reproduce this issue, I will close it for now. Happy to reopen it if this issue persists!

**Closed by andrewhead** 2021-03-02 14:22 UTC
Labels: api
